In [1]:
import pandas as pd
import os
# need to have openpyxl installed

In [2]:
cwd = os.getcwd()

In [3]:
####################################
### GAS TRANSMISSION & GATHERING ###
####################################

In [4]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# 2001-2009 3. MILES OF PIPE BY DECADE OF INSTALLATION
mi_cols_01_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'B3TON_T', # total for that year
                 'B3TON_1', 'B3TON_2', 'B3TON_3', 'B3TON_4', 'B3TON_5', 'B3TON_6', # totals by decade installed
                 'B3TON_7', 'B3TON_8', 'B3TON_9'] # totals by decade installed
# 2010-present PART J – MILES OF PIPE BY DECADE INSTALLED
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                 "PARTJTONTOTAL", # total for that year
                 "PARTJTONUNKWN", "PARTJTONPRE1940", "PARTJTON194049", "PARTJTON195059", "PARTJTON196069", "PARTJTON197079", # totals by decade installed
                 "PARTJTON198089", "PARTJTON199099", "PARTJTON200009", "PARTJTON201019", "PARTJTON202029"] # totals by decade installed
# and a dictionary to map names
col_map = dict(zip(mi_cols_01_09,mi_cols_10_25))

In [5]:
# start with Rebecca's snippet for gas transmission & gathering 2010-present
data_path_gt_10_25 = os.path.join(cwd, "data\\annual_gas_transmission_gathering_2010_present")
fl_10_25 = os.listdir(data_path_gt_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

gt_ontot_partj_10_25 = pd.DataFrame()

#excl = ('2010.xlsx', '2011.xlsx')
for f in xlsx_fl_10_25:
    #if any(f.endswith(excl) for yrs in excl): continue
    #else:
    data = pd.read_excel(os.path.join(data_path_gt_10_25,f), sheet_name="GT AR Part J", header = 2, usecols=mi_cols_10_25)
    gt_ontot_partj_10_25 = pd.concat([gt_ontot_partj_10_25, data])

In [6]:
gt_ontot_partj_10_25

,REPORT_YEAR,REPORT_NUMBER,OPERATOR_ID,PARTJTONUNKWN,PARTJTONPRE1940,PARTJTON194049,PARTJTON195059,PARTJTON196069,PARTJTON197079,PARTJTON198089,PARTJTON199099,PARTJTON200009,PARTJTON201019,PARTJTON202029,PARTJTONTOTAL
0,2010,20110198,3,0.0,0.0,57.336,28.358,219.116,56.484,62.125,17.728,2.906,0.000,NaN,444.053
1,2010,20110759,21,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,87.500,0.000,NaN,87.500
2,2010,20110934,117,0.0,0.0,45.000,0.000,0.000,0.000,0.000,0.000,84.000,0.000,NaN,129.000
3,2010,20110934,117,0.0,0.0,0.000,0.000,3.000,0.000,2.000,2.000,8.000,1.000,NaN,16.000
4,2010,20110934,117,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,NaN,1.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2069,2025,20261450,41185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2070,2025,20261448,41187,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,1.300,0.000,0.00,1.300
2071,2025,20261452,41200,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.013,0.00,0.013
2072,2025,20261453,41214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2073,2025,20261107,99054,0.0,0.0,0.000,0.790,0.000,0.000,0.510,12.540,0.720,0.980,0.66,16.200

In [7]:
# continue with gas transmission & gathering 2001-2009
data_path_gt_01_09 = os.path.join(cwd, "data\\annual_gas_transmission_gathering_2001_2009")
fl_01_09 = os.listdir(data_path_gt_01_09)
xlsx_fl_01_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_01_09))

gt_ontot_partj_01_09 = pd.DataFrame()

for f in xlsx_fl_01_09:
    data = pd.read_excel(os.path.join(data_path_gt_01_09,f), usecols = mi_cols_01_09)
    gt_ontot_partj_01_09 = pd.concat([gt_ontot_partj_01_09, data])

In [8]:
# rename columns to match 2010-present data format
gt_ontot_partj_01_09 = gt_ontot_partj_01_09.rename(mapper=col_map, axis=1)
# combine the two timeframes
gt_ontot_partj_01_25 = pd.concat([gt_ontot_partj_01_09, gt_ontot_partj_10_25])
# see the result
gt_ontot_partj_01_25 = gt_ontot_partj_01_25.groupby('REPORT_YEAR').sum()['PARTJTONTOTAL']
gt_ontot_partj_01_25.name = 'gas_trans_mi'
gt_ontot_partj_01_25

REPORT_YEAR
2001    284452.820
2002    296794.134
2003    295402.842
2004    296944.828
2005    294800.268
2006    293705.627
2007    294938.972
2008    297267.428
2009    298964.403
2010    299360.490
2011    299730.085
2012    298612.895
2013    298378.453
2014    297901.881
2015    297334.908
2016    296984.816
2017    297580.471
2018    298522.722
2019    298909.750
2020    298836.677
2021    298754.690
2022    298111.272
2023    297682.161
2024    298033.135
2025    297363.106
Name: gas_trans_mi, dtype: float64

In [9]:
########################
### GAS DISTRIBUTION ###
########################

In [10]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# 2004-2009 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'DINSTMT', # total for that year
                 'DINSTM_1', 'DINSTM_2', 'DINSTM_3', 'DINSTM_4', 'DINSTM_5', 'DINSTM_6', 'DINSTM_7', 'DINSTM_8', 'DINSTM_9'] # totals by decade installed
# 2010-present 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                 "MMILES_BY_DCD_TOTAL", # total for that year
                 "MMILES_BY_DCD_UNK", "MMILES_BY_DCD_PRE1940", "MMILES_BY_DCD_1940_TO_1949", "MMILES_BY_DCD_1950_TO_1959", 
                 "MMILES_BY_DCD_1960_TO_1969", "MMILES_BY_DCD_1970_TO_1979", # totals by decade installed
                 "MMILES_BY_DCD_1980_TO_1989", "MMILES_BY_DCD_1990_TO_1999", "MMILES_BY_DCD_2000_TO_2009", 
                 "MMILES_BY_DCD_2010_TO_2019", "MMILES_BY_DCD_2020_TO_2029"] # totals by decade installed
# and a dictionary to map names
col_map = dict(zip(mi_cols_04_09,mi_cols_10_25))

In [11]:
# gas distribution 2004-2009
data_path_gd_04_09 = os.path.join(cwd, "data\\annual_gas_distribution_2004_2009")
fl_04_09 = os.listdir(data_path_gd_04_09)
xlsx_fl_04_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_04_09))

gd_ontot_04_09 = pd.DataFrame()

for f in xlsx_fl_04_09:
    data = pd.read_excel(os.path.join(data_path_gd_04_09,f), usecols = mi_cols_04_09)
    gd_ontot_04_09 = pd.concat([gd_ontot_04_09, data])

In [12]:
gd_ontot_04_09

,YR,RPTID,OPERATOR_ID,DINSTM_1,DINSTM_2,DINSTM_3,DINSTM_4,DINSTM_5,DINSTM_6,DINSTM_7,DINSTM_8,DINSTM_9,DINSTMT
0,2004,20040230,5280,0.00,0.00,0.00,4.00,8.00,0.00,29.00,5.000,3.000,49.00
1,2004,20040406,12186,0.00,0.00,0.00,0.00,36.00,6.00,12.00,16.000,0.000,70.00
2,2004,20040407,2060,152.00,0.00,0.00,0.00,0.00,0.00,0.00,0.000,0.000,152.00
3,2004,20040055,7300,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.000,41.000,41.00
4,2004,20040286,18124,0.00,0.00,0.00,40.00,29.00,36.00,11.00,122.000,25.000,263.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,2009,20090050,5057,0.00,5.02,2.96,10.34,7.96,0.95,0.00,5.210,3.200,35.64
1445,2009,20090126,31093,0.00,0.00,0.00,0.00,0.00,0.00,0.00,27.000,2.370,29.37
1446,2009,20090181,22168,1.59,0.00,0.00,0.00,9.00,0.50,1.65,1.705,0.975,15.42
1447,2009,20090129,11624,12.95,0.00,0.00,0.00,0.00,0.00,0.00,16.250,0.000,29.20
1448,2009,20090727,2860,0.00,0.00,0.00,144.40,38.60,21.00,11.00,25.900,81.400,322.30

In [13]:
# gas distribution 2010-present
data_path_gd_10_25 = os.path.join(cwd, "data\\annual_gas_distribution_2010_present")
fl_10_25 = os.listdir(data_path_gd_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

gd_ontot_10_25 = pd.DataFrame()

for f in xlsx_fl_10_25:
    data = pd.read_excel(os.path.join(data_path_gd_10_25,f), header = 2, usecols=mi_cols_10_25)
    gd_ontot_10_25 = pd.concat([gd_ontot_10_25, data])

In [14]:
# rename columns to match 2010-present data format
gd_ontot_04_09 = gd_ontot_04_09.rename(mapper=col_map, axis=1)
# combine the two timeframes
gd_ontot_04_25 = pd.concat([gd_ontot_04_09, gd_ontot_10_25])
# see the result
gd_ontot_04_25 = gd_ontot_04_25.groupby('REPORT_YEAR').sum()['MMILES_BY_DCD_TOTAL']
gd_ontot_04_25.name = "gas_dist_mi"
gd_ontot_04_25

REPORT_YEAR
2004    1142296.704
2005    1165020.196
2006    1188084.830
2007    1203330.239
2008    1210032.073
2009    1220539.274
2010    1229922.162
2011    1239282.914
2012    1245535.791
2013    1255308.558
2014    1266366.494
2015    1275553.142
2016    1285747.081
2017    1297231.338
2018    1308215.046
2019    1319464.077
2020    1329840.956
2021    1341274.034
2022    1356500.805
2023    1367882.401
2024    1379720.247
2025    1394660.558
Name: gas_dist_mi, dtype: float64

In [15]:
########################
### HAZARDOUS LIQUID ###
########################

In [16]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# NOTE: hazardous liquids use different time intervals than gas transmission/distribution
# 2004 - 2009
# PART D - MILES OF PIPE BY DECADE INSTALLED
mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'DINSTMT', # total for that year
                 'DINSTM_1', # Pre-20 or Unknown
                 'DINSTM_2', # 1920-1929
                 'DINSTM_3', # 1930-1939
                 'DINSTM_4', # 1940-1949
                 'DINSTM_5', # 1950-1959
                 'DINSTM_6', # 1960-1969
                 'DINSTM_7', # 1970-1979
                 'DINSTM_8', # 1980-1989
                 'DINSTM_9', # 1990-1999
                 'DINSTM_10'] # 2000-2009
# 2010 - present
# PART I - MILES OF PIPE BY DECADE INSTALLED
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                 "PARTITOTAL", # total for that year
                 "PARTIUNKWN", # Unknown
                 'PARTIPRE20', # Pre-20s
                 'PARTI192029', # 1920-1929
                 'PARTI193039', # 1930-1939
                 'PARTI194049', # 1940-1949
                 'PARTI195059', # 1950-1959
                 'PARTI196069', # 1960-1969
                 'PARTI197079', # 1970-1979
                 'PARTI198089', # 1980-1989
                 'PARTI199099', # 1990-1999
                 'PARTI200009', # 2000-2009
                 'PARTI201019', # 2010-2019
                 'PARTI202029'] # 2020-2029

In [17]:
# hazardous liquid 2004-2009
data_path_hl_04_09 = os.path.join(cwd, "data\\annual_hazardous_liquid_2004_2009")
fl_04_09 = os.listdir(data_path_hl_04_09)
xlsx_fl_04_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_04_09))

hl_04_09 = pd.DataFrame()

for f in xlsx_fl_04_09:
    data = pd.read_excel(os.path.join(data_path_hl_04_09,f), usecols = mi_cols_04_09)
    hl_04_09 = pd.concat([hl_04_09, data])

In [18]:
hl_04_09

,YR,RPTID,OPERATOR_ID,DINSTM_1,DINSTM_2,DINSTM_3,DINSTM_4,DINSTM_5,DINSTM_6,DINSTM_7,DINSTM_8,DINSTM_9,DINSTM_10,DINSTMT
0,2004,20040233,300,5.00,557.00,224.00,1411.00,402.00,549.0,193.00,203.000,80.00,182.000,3806.000
1,2004,20040315,32011,0.00,0.00,0.00,0.00,180.00,13.0,0.00,92.000,160.50,0.000,445.500
2,2004,20040435,31045,16.96,58.13,57.89,134.48,94.33,20.0,102.13,5.470,54.15,4.710,548.250
3,2004,20040066,8166,0.00,0.00,0.00,0.00,0.00,0.0,50.00,0.000,0.00,0.000,50.000
4,2004,20040193,22430,0.00,0.00,0.00,0.00,4.00,0.0,0.00,0.000,0.00,0.000,4.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,2009,20090231,31579,0.00,0.00,0.00,0.00,0.00,11.0,0.00,2.000,0.00,1.000,14.000
479,2009,20090216,10346,0.00,0.00,0.00,0.00,0.00,0.0,0.00,32.744,0.00,4.118,36.862
480,2009,20090195,31957,0.00,0.00,0.00,75.00,370.00,0.0,0.00,0.000,0.00,11.000,456.000
481,2009,20090341,31973,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.000,7.00,0.000,7.000
482,2009,20090348,26112,0.00,0.00,0.00,0.00,1.47,0.0,0.00,0.000,0.00,0.000,1.470

In [19]:
# hazardous liquid 2010-present
data_path_hl_10_25 = os.path.join(cwd, "data\\annual_hazardous_liquid_2010_present")
fl_10_25 = os.listdir(data_path_hl_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

hl_10_25 = pd.DataFrame()

for f in xlsx_fl_10_25:
    data = pd.read_excel(os.path.join(data_path_hl_10_25,f), sheet_name="HL AR Part I", header = 2, usecols=mi_cols_10_25)
    hl_10_25 = pd.concat([hl_10_25, data])

In [20]:
hl_10_25

,REPORT_YEAR,REPORT_NUMBER,OPERATOR_ID,PARTIUNKWN,PARTIPRE20,PARTI192029,PARTI193039,PARTI194049,PARTI195059,PARTI196069,PARTI197079,PARTI198089,PARTI199099,PARTI200009,PARTI201019,PARTI202029,PARTITOTAL
0,2010,20110334,300,NaN,NaN,NaN,NaN,NaN,6.390,NaN,11.340,NaN,12.990,4.820,NaN,NaN,35.540
1,2010,20110334,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.020,NaN,NaN,NaN,NaN,138.020
2,2010,20110334,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.640,NaN,NaN,NaN,NaN,9.640
3,2010,20110334,300,NaN,NaN,NaN,NaN,NaN,56.460,1.500,NaN,0.090,0.380,NaN,NaN,NaN,58.430
4,2010,20110334,300,NaN,NaN,NaN,NaN,NaN,NaN,8.880,NaN,9.620,10.810,4.390,NaN,NaN,33.700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390,2025,20260198,99031,0.187,0.0,0.0,0.0,2.007,0.000,0.000,0.000,0.000,0.000,0.101,0.067,0.176,2.538
1391,2025,20260198,99031,0.000,0.0,0.0,0.0,0.000,0.255,0.000,0.000,0.000,0.200,0.000,0.000,0.000,0.455
1392,2025,20260198,99031,0.000,0.0,0.0,0.0,1.724,0.000,0.279,0.512,7.104,0.125,0.238,0.002,0.745,10.729
1393,2025,20260198,99031,0.000,0.0,0.0,0.0,0.811,0.000,0.000,0.101,0.000,0.000,0.277,0.000,1.058,2.247
1394,2025,20260048,99043,0.000,NaN,0.0,0.0,0.000,2.263,0.000,0.000,0.000,0.000,0.007,0.830,0.000,3.100

In [21]:
# group by year and calculate sum
# 2004-2009
hl_04_09 = hl_04_09.groupby('YR').sum()['DINSTMT']
hl_04_09

YR
2004    166669.407
2005    166760.145
2006    166718.875
2007    169846.126
2008    173789.064
2009    175965.482
Name: DINSTMT, dtype: float64

In [22]:
# group by year and calculate sum
# 2010-2025
hl_10_25 = hl_10_25.groupby('REPORT_YEAR').sum()['PARTITOTAL']
hl_10_25

REPORT_YEAR
2010    181836.069
2011    183574.594
2012    186411.359
2013    192602.050
2014    199984.244
2015    208811.865
2016    212354.034
2017    216236.517
2018    219327.298
2019    225498.994
2020    229390.720
2021    230035.833
2022    229366.487
2023    228758.068
2024    228377.552
2025    228207.188
Name: PARTITOTAL, dtype: float64

In [23]:
# combine the two timeframes
hl_04_09 = hl_04_09.rename({'YR':'REPORT_YEAR', 'DINSTMT':'PARTITOTAL'})
hl_04_25 = pd.concat([hl_04_09, hl_10_25])
hl_04_25.name = 'haz_liq_mi'
hl_04_25

2004    166669.407
2005    166760.145
2006    166718.875
2007    169846.126
2008    173789.064
2009    175965.482
2010    181836.069
2011    183574.594
2012    186411.359
2013    192602.050
2014    199984.244
2015    208811.865
2016    212354.034
2017    216236.517
2018    219327.298
2019    225498.994
2020    229390.720
2021    230035.833
2022    229366.487
2023    228758.068
2024    228377.552
2025    228207.188
Name: haz_liq_mi, dtype: float64

In [24]:
################
### COMBINED ###
################

In [37]:
# combine the mileages
phmsa_ann_mi = pd.concat([gt_ontot_partj_01_25, gd_ontot_04_25, hl_04_25], axis=1)
phmsa_ann_mi['ann_tot_mi'] = phmsa_ann_mi.sum(axis=1)

In [38]:
# drop years before 2005 to match blog post time frame
phmsa_ann_mi = phmsa_ann_mi.loc[2005:2025]

In [39]:
output_file = os.path.join(cwd,'phmsa_ann_mi.csv')
phmsa_ann_mi.to_csv(output_file, index_label='Year')

In [40]:
phmsa_ann_mi.index

Index([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
      dtype='int64')