In [192]:
import pandas as pd
import os
# need to have openpyxl installed

In [193]:
cwd = os.getcwd()

In [ ]:
####################################
### GAS TRANSMISSION & GATHERING ###
####################################

In [ ]:
# # PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# # 2001-2009 3. MILES OF PIPE BY DECADE OF INSTALLATION
# mi_cols_01_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
#                  'B3TON_T', 'B3TOTAL_T', # total for that year (onshore, on+offshore)
#                  'B3TON_1', 'B3TON_2', 'B3TON_3', 'B3TON_4', 'B3TON_5', 'B3TON_6', # totals by decade installed
#                  'B3TON_7', 'B3TON_8', 'B3TON_9'] # totals by decade installed
# # 2010-present PART J – MILES OF PIPE BY DECADE INSTALLED
# mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
#                  "PARTJTONTOTAL", "PARTJTTOTAL", # total for that year (onshore, on+offshore)
#                  "PARTJTONUNKWN", "PARTJTONPRE1940", "PARTJTON194049", "PARTJTON195059", "PARTJTON196069", "PARTJTON197079", # totals by decade installed
#                  "PARTJTON198089", "PARTJTON199099", "PARTJTON200009", "PARTJTON201019", "PARTJTON202029"] # totals by decade installed
# # and a dictionary to map names
# col_map = dict(zip(mi_cols_01_09,mi_cols_10_25))

In [194]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# 2001-2009 3. MILES OF PIPE BY DECADE OF INSTALLATION
mi_cols_01_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'B3TOTAL_T'] # mileage total for onshore + offshore for all transmission
                
# 2010-present PART J – MILES OF PIPE BY DECADE INSTALLED
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                 "PARTJTTOTAL","PARTJGTOTAL"] # mileage total for onshore + offshore for all transmission, all gathering
                 
# and a dictionary to map names
col_map = dict(zip(mi_cols_01_09,mi_cols_10_25))

In [195]:
# start with Rebecca's snippet for gas transmission & gathering 2010-present
data_path_gt_10_25 = os.path.join(cwd, "data/annual_gas_transmission_gathering_2010_present")
fl_10_25 = os.listdir(data_path_gt_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

gtgg_tot_partj_10_25 = pd.DataFrame()

#excl = ('2010.xlsx', '2011.xlsx')
for f in xlsx_fl_10_25:
    #if any(f.endswith(excl) for yrs in excl): continue
    #else:
    data = pd.read_excel(os.path.join(data_path_gt_10_25,f), sheet_name="GT AR Part J", header = 2, usecols=mi_cols_10_25)
    gtgg_tot_partj_10_25 = pd.concat([gtgg_tot_partj_10_25, data])

In [196]:
# continue with gas transmission & gathering 2001-2009
data_path_gt_01_09 = os.path.join(cwd, "data/annual_gas_transmission_gathering_2001_2009")
fl_01_09 = os.listdir(data_path_gt_01_09)
xlsx_fl_01_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_01_09))

gt_tot_partj_01_09 = pd.DataFrame()

for f in xlsx_fl_01_09:
    data = pd.read_excel(os.path.join(data_path_gt_01_09,f), usecols = mi_cols_01_09)
    gt_tot_partj_01_09 = pd.concat([gt_tot_partj_01_09, data])

In [197]:
# combine gt and gg for 2010-2025
gt_tot_partj_10_25 = gtgg_tot_partj_10_25.groupby('REPORT_YEAR').sum()['PARTJTTOTAL']
gg_tot_partj_10_25 = gtgg_tot_partj_10_25.groupby('REPORT_YEAR').sum()['PARTJGTOTAL']
gtgg_sum_partj_10_25 = gt_tot_partj_10_25 + gg_tot_partj_10_25
gtgg_sum_partj_10_25.name = 'PARTJTTOTAL'

# rename columns to match 2010-present data format
gt_tot_partj_01_09 = gt_tot_partj_01_09.rename(mapper=col_map, axis=1)
# calculate annual mileage
gt_tot_partj_01_09 = gt_tot_partj_01_09.groupby('REPORT_YEAR').sum()['PARTJTTOTAL']
# combine the two timeframes
gtgg_tot_partj_01_25 = pd.concat([gt_tot_partj_01_09, gtgg_sum_partj_10_25])
# see the result
gtgg_tot_partj_01_25.name = 'gas_trans_gather_mi'
gtgg_tot_partj_01_25

REPORT_YEAR
2001    311391.025
2002    325740.986
2003    324492.252
2004    327993.527
2005    324222.120
2006    321221.911
2007    321108.448
2008    322912.966
2009    324936.308
2010    324458.195
2011    324335.585
2012    319914.253
2013    320245.774
2014    319354.264
2015    318948.739
2016    318145.313
2017    318833.923
2018    319543.718
2019    320128.107
2020    319234.677
2021    318683.634
2022    413278.840
2023    412027.061
2024    411847.068
2025    413359.474
Name: gas_trans_gather_mi, dtype: float64

In [ ]:
########################
### GAS DISTRIBUTION ###
########################

In [ ]:
# # PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# # 2004-2009 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
# mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
#                  'DINSTMT', # total for that year
#                  'DINSTM_1', 'DINSTM_2', 'DINSTM_3', 'DINSTM_4', 'DINSTM_5', 'DINSTM_6', 'DINSTM_7', 'DINSTM_8', 'DINSTM_9'] # totals by decade installed
# # 2010-present 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
# mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
#                 "MMILES_TOTAL", "NUM_SRVCS_TOTAL", "AVERAGE_LENGTH", 
#                  "MMILES_BY_DCD_TOTAL", # total for that year
#                  "MMILES_BY_DCD_UNK", "MMILES_BY_DCD_PRE1940", "MMILES_BY_DCD_1940_TO_1949", "MMILES_BY_DCD_1950_TO_1959", 
#                  "MMILES_BY_DCD_1960_TO_1969", "MMILES_BY_DCD_1970_TO_1979", # totals by decade installed
#                  "MMILES_BY_DCD_1980_TO_1989", "MMILES_BY_DCD_1990_TO_1999", "MMILES_BY_DCD_2000_TO_2009", 
#                  "MMILES_BY_DCD_2010_TO_2019", "MMILES_BY_DCD_2020_TO_2029"] # totals by decade installed
# # and a dictionary to map names
# col_map = dict(zip(mi_cols_04_09,mi_cols_10_25))

In [199]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# 2004-2009 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'B1MT', 'B1ST', 'AVER'] # totals for that year
# 2010-present 4. MILES OF MAIN AND NUMBER OF SERVICES BY DECADE OF INSTALLATION
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                "MMILES_TOTAL", "NUM_SRVCS_TOTAL", "AVERAGE_LENGTH"] # totals for that year
                 
# and a dictionary to map names
col_map = dict(zip(mi_cols_04_09,mi_cols_10_25))

In [200]:
# gas distribution 2004-2009
data_path_gd_04_09 = os.path.join(cwd, "data/annual_gas_distribution_2004_2009")
fl_04_09 = os.listdir(data_path_gd_04_09)
xlsx_fl_04_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_04_09))

gd_tot_04_09 = pd.DataFrame()

for f in xlsx_fl_04_09:
    data = pd.read_excel(os.path.join(data_path_gd_04_09,f), usecols = mi_cols_04_09)
    gd_tot_04_09 = pd.concat([gd_tot_04_09, data])

In [201]:
# gas distribution 2010-present
data_path_gd_10_25 = os.path.join(cwd, "data/annual_gas_distribution_2010_present")
fl_10_25 = os.listdir(data_path_gd_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

gd_tot_10_25 = pd.DataFrame()

for f in xlsx_fl_10_25:
    data = pd.read_excel(os.path.join(data_path_gd_10_25,f), header = 2, usecols=mi_cols_10_25)
    gd_tot_10_25 = pd.concat([gd_tot_10_25, data])

In [202]:
# rename columns to match 2010-present data format
gd_tot_04_09 = gd_tot_04_09.rename(mapper=col_map, axis=1)
# combine the two timeframes
gd_tot_04_25 = pd.concat([gd_tot_04_09, gd_tot_10_25])
# calculate the estimated service mileage and sum to total mileage
gd_tot_04_25["SRVC_MILES_EST"] = gd_tot_04_25["NUM_SRVCS_TOTAL"] * gd_tot_04_25['AVERAGE_LENGTH'] / 5280
# add main + est service to calculate the total (estimated) gd mileage
gd_tot_04_25["TOTAL_MILES_EST"] = gd_tot_04_25["SRVC_MILES_EST"] + gd_tot_04_25["MMILES_TOTAL"]
# see the result
gd_tot_04_25 = gd_tot_04_25.groupby('REPORT_YEAR').sum()['TOTAL_MILES_EST']
gd_tot_04_25.name = "gas_dist_mi"
gd_tot_04_25

REPORT_YEAR
2004    1.917834e+06
2005    1.947070e+06
2006    1.963770e+06
2007    2.018745e+06
2008    2.054465e+06
2009    2.081728e+06
2010    2.101546e+06
2011    2.120589e+06
2012    2.102016e+06
2013    2.138996e+06
2014    2.154242e+06
2015    2.188716e+06
2016    2.210477e+06
2017    2.225838e+06
2018    2.239067e+06
2019    2.264471e+06
2020    2.284683e+06
2021    2.300013e+06
2022    2.321816e+06
2023    2.350285e+06
2024    2.372081e+06
2025    2.398815e+06
Name: gas_dist_mi, dtype: float64

In [ ]:
########################
### HAZARDOUS LIQUID ###
########################

In [ ]:
# # PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# # NOTE: hazardous liquids use different time intervals than gas transmission/distribution
# # 2004 - 2009
# # PART D - MILES OF PIPE BY DECADE INSTALLED
# mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
#                  'DINSTMT', # total for that year
#                  'DINSTM_1', # Pre-20 or Unknown
#                  'DINSTM_2', # 1920-1929
#                  'DINSTM_3', # 1930-1939
#                  'DINSTM_4', # 1940-1949
#                  'DINSTM_5', # 1950-1959
#                  'DINSTM_6', # 1960-1969
#                  'DINSTM_7', # 1970-1979
#                  'DINSTM_8', # 1980-1989
#                  'DINSTM_9', # 1990-1999
#                  'DINSTM_10'] # 2000-2009
# # 2010 - present
# # PART I - MILES OF PIPE BY DECADE INSTALLED
# mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
#                  "PARTITOTAL", # total for that year
#                  "PARTIUNKWN", # Unknown
#                  'PARTIPRE20', # Pre-20s
#                  'PARTI192029', # 1920-1929
#                  'PARTI193039', # 1930-1939
#                  'PARTI194049', # 1940-1949
#                  'PARTI195059', # 1950-1959
#                  'PARTI196069', # 1960-1969
#                  'PARTI197079', # 1970-1979
#                  'PARTI198089', # 1980-1989
#                  'PARTI199099', # 1990-1999
#                  'PARTI200009', # 2000-2009
#                  'PARTI201019', # 2010-2019
#                  'PARTI202029'] # 2020-2029

In [203]:
# PHMSA's data collection form changed between 2009-2010 so different sets of column names are needed
# NOTE: hazardous liquids use different time intervals than gas transmission/distribution
# 2004 - 2009
# PART D - MILES OF PIPE BY DECADE INSTALLED
mi_cols_04_09 = ['RPTID', 'YR', 'OPERATOR_ID', # operator info
                 'DINSTMT'] # total for that year
        
# 2010 - present
# PART I - MILES OF PIPE BY DECADE INSTALLED
mi_cols_10_25 = ["REPORT_NUMBER", "REPORT_YEAR", "OPERATOR_ID", # operator info
                 "PARTITOTAL"] # total for that year
                 
# and a dictionary to map names
col_map = dict(zip(mi_cols_04_09,mi_cols_10_25))

In [204]:
# hazardous liquid 2004-2009
data_path_hl_04_09 = os.path.join(cwd, "data/annual_hazardous_liquid_2004_2009")
fl_04_09 = os.listdir(data_path_hl_04_09)
xlsx_fl_04_09 = list(filter(lambda f: f.endswith('.xlsx'), fl_04_09))

hl_04_09 = pd.DataFrame()

for f in xlsx_fl_04_09:
    data = pd.read_excel(os.path.join(data_path_hl_04_09,f), usecols = mi_cols_04_09)
    hl_04_09 = pd.concat([hl_04_09, data])

In [205]:
# hazardous liquid 2010-present
data_path_hl_10_25 = os.path.join(cwd, "data/annual_hazardous_liquid_2010_present")
fl_10_25 = os.listdir(data_path_hl_10_25)
xlsx_fl_10_25 = list(filter(lambda f: f.endswith('.xlsx'), fl_10_25))

hl_10_25 = pd.DataFrame()

for f in xlsx_fl_10_25:
    data = pd.read_excel(os.path.join(data_path_hl_10_25,f), sheet_name="HL AR Part I", header = 2, usecols=mi_cols_10_25)
    hl_10_25 = pd.concat([hl_10_25, data])

In [206]:
hl_10_25

      REPORT_YEAR  REPORT_NUMBER  OPERATOR_ID  PARTITOTAL
0            2017       20183395          300      52.630
1            2017       20183395          300     282.150
2            2017       20183395          300     137.210
3            2017       20183395          300     168.070
4            2017       20183395          300      58.510
...           ...            ...          ...         ...
1240         2014       20151617        99031       0.255
1241         2014       20151617        99031      10.722
1242         2014       20151617        99031       1.189
1243         2014       20151675        99037      29.470
1244         2014       20151593        99043       3.100

[21176 rows x 4 columns]

In [207]:
# rename columns to match 2010-present data format
hl_04_09 = hl_04_09.rename(mapper=col_map, axis=1)
# combine the two timeframes
hl_04_25 = pd.concat([hl_04_09, hl_10_25])
# groupby year and calculate sum
hl_04_25 = hl_04_25.groupby('REPORT_YEAR').sum()['PARTITOTAL']
hl_04_25.name = 'haz_liq_mi'
hl_04_25

REPORT_YEAR
2004    166669.407
2005    166760.145
2006    166718.875
2007    169846.126
2008    173789.064
2009    175965.482
2010    181836.069
2011    183574.594
2012    186411.359
2013    192602.050
2014    199984.244
2015    208811.865
2016    212354.034
2017    216236.517
2018    219327.298
2019    225498.994
2020    229390.720
2021    230035.833
2022    229366.487
2023    228758.068
2024    228377.552
2025    228242.188
Name: haz_liq_mi, dtype: float64

In [ ]:
################
### COMBINED ###
################

In [208]:
# combine the mileages
phmsa_ann_mi = pd.concat([gtgg_tot_partj_01_25, gd_tot_04_25, hl_04_25], axis=1)
phmsa_ann_mi['ann_tot_mi'] = phmsa_ann_mi.sum(axis=1)

In [209]:
# drop years before 2005 to match blog post time frame
phmsa_ann_mi = phmsa_ann_mi.loc[2005:2025]

In [211]:
output_file = os.path.join(cwd,'phmsa_ann_mi.csv')
phmsa_ann_mi.to_csv(output_file, index_label='Year')

In [ ]:
phmsa_ann_mi.index

In [210]:
phmsa_ann_mi

             gas_trans_gather_mi   gas_dist_mi  haz_liq_mi    ann_tot_mi
REPORT_YEAR
2005                  324222.120  1.947070e+06  166760.145  2.438052e+06
2006                  321221.911  1.963770e+06  166718.875  2.451711e+06
2007                  321108.448  2.018745e+06  169846.126  2.509700e+06
2008                  322912.966  2.054465e+06  173789.064  2.551167e+06
2009                  324936.308  2.081728e+06  175965.482  2.582630e+06
2010                  324458.195  2.101546e+06  181836.069  2.607841e+06
2011                  324335.585  2.120589e+06  183574.594  2.628499e+06
2012                  319914.253  2.102016e+06  186411.359  2.608342e+06
2013                  320245.774  2.138996e+06  192602.050  2.651843e+06
2014                  319354.264  2.154242e+06  199984.244  2.673581e+06
2015                  318948.739  2.188716e+06  208811.865  2.716477e+06
2016                  318145.313  2.210477e+06  212354.034  2.740976e+06
2017                  318833.923  2.225838e+06  216236.517  2.760908e+06
2018                  319543.718  2.239067e+06  219327.298  2.777938e+06
2019                  320128.107  2.264471e+06  225498.994  2.810098e+06
2020                  319234.677  2.284683e+06  229390.720  2.833308e+06
2021                  318683.634  2.300013e+06  230035.833  2.848733e+06
2022                  413278.840  2.321816e+06  229366.487  2.964462e+06
2023                  412027.061  2.350285e+06  228758.068  2.991070e+06
2024                  411847.068  2.372081e+06  228377.552  3.012306e+06
2025                  413359.474  2.398815e+06  228242.188  3.040416e+06